### ISSUE TITLE
同时匹配多个语言

### ISSUE THREAD

**Issue by Songggggr** [JoeyLearnsToCode/vscode-custom-postfix-completion#2]
插件非常好用，但是不支持匹配多个语言，例如用同一套模板匹配 js、ts、jsx、tsx、vue 等等。
设想是 langauge key 中支持 "," 分割多个语言，使其支持同一套模板。

**Comment by Songggggr** [comment]
PR 已经提了，辛苦 review  下 @JoeyLearnsToCode 
#3

**Comment by JoeyLearnsToCode** [comment]
谢谢贡献
